<?php

namespace App\Http\Controllers\Admin;

use App\Http\Controllers\Controller;
use App\Models\Company;
use App\Models\User;
use Carbon\Carbon;
use Illuminate\Http\Request;
use Illuminate\Support\Facades\DB;
use Illuminate\Support\Facades\Storage;
use Illuminate\Validation\Rule;

class BackupController extends Controller
{
    private $exportableTables = [
        'users' => 'Пользователи',
        'companies' => 'Компании',
        'payments' => 'Платежи',
        'claims' => 'Убытки',
        'contracts' => 'Договоры'
    ];
    
    public function index()
    {
        $backupFiles = $this->getBackupFiles();
        
        return view('admin.backup.index', [
            'exportableTables' => $this->exportableTables,
            'backupFiles' => $backupFiles,
        ]);
    }
    
    public function create(Request $request)
    {
        $request->validate([
            'tables' => 'required|array',
            'tables.*' => 'string|in:' . implode(',', array_keys($this->exportableTables)),
            'include_structure' => 'boolean',
            'compress' => 'boolean',
        ]);
        
        try {
            $tables = $request->input('tables', []);
            $includeStructure = $request->boolean('include_structure', true);
            $compress = $request->boolean('compress', false);
            
            $timestamp = Carbon::now()->format('Y-m-d_H-i-s');
            $backupName = "backup_{$timestamp}";
            
            $sqlContent = $this->generateSqlBackup($tables, $includeStructure);
            
            $sqlFileName = "{$backupName}.sql";
            Storage::disk('backups')->put($sqlFileName, $sqlContent);
            
            $finalFileName = $sqlFileName;
            if ($compress) {
                $finalFileName = $this->compressBackup($sqlFileName, $backupName);
            }
            
            return response()->json([
                'success' => true,
                'message' => 'Резервная копия успешно создана',
                'file' => $finalFileName,
                'download_url' => route('admin.backup.download', ['filename' => $finalFileName]),
            ]);
            
        } catch (\Exception $e) {
            return response()->json([
                'success' => false,
                'message' => 'Ошибка при создании резервной копии: ' . $e->getMessage(),
            ], 500);
        }
    }
    
    public function download($filename)
    {
        if (!Storage::disk('backups')->exists($filename)) {
            abort(404, 'Файл не найден');
        }
        
        $extension = pathinfo($filename, PATHINFO_EXTENSION);
        $contentType = $extension === 'zip' ? 'application/zip' : 'application/sql';
        
        return Storage::disk('backups')->download($filename, $filename, [
            'Content-Type' => $contentType,
        ]);
    }
    
    public function delete($filename)
    {
        try {
            if (Storage::disk('backups')->exists($filename)) {
                Storage::disk('backups')->delete($filename);
                
                return response()->json([
                    'success' => true,
                    'message' => 'Резервная копия удалена',
                ]);
            }
            
            return response()->json([
                'success' => false,
                'message' => 'Файл не найден',
            ], 404);
            
        } catch (\Exception $e) {
            return response()->json([
                'success' => false,
                'message' => 'Ошибка при удалении файла',
            ], 500);
        }
    }
    
    private function generateSqlBackup(array $tables, bool $includeStructure = true): string
    {
        $sql = "-- Backup generated: " . Carbon::now()->toDateTimeString() . "\n";
        $sql .= "-- Generated by: " . auth()->user()->name . " (" . auth()->user()->email . ")\n";
        $sql .= "SET FOREIGN_KEY_CHECKS=0;\n\n";
        
        foreach ($tables as $table) {
            if (!in_array($table, array_keys($this->exportableTables))) {
                continue;
            }
            
            if ($includeStructure) {
                $structure = DB::select("SHOW CREATE TABLE `{$table}`");
                $sql .= "-- Структура таблицы `{$table}`\n";
                $sql .= "DROP TABLE IF EXISTS `{$table}`;\n";
                $sql .= $structure[0]->{'Create Table'} . ";\n\n";
            }
            
            $rows = DB::table($table)->get();
            
            if ($rows->count() > 0) {
                $sql .= "-- Данные таблицы `{$table}`\n";
                
                $columns = array_keys((array) $rows->first());
                
                foreach ($rows->chunk(100) as $chunk) {
                    $sql .= "INSERT INTO `{$table}` (`" . implode('`, `', $columns) . "`) VALUES \n";
                    
                    $values = [];
                    foreach ($chunk as $row) {
                        $rowValues = [];
                        foreach ($columns as $column) {
                            $value = $row->$column;
                            
                            if ($value === null) {
                                $rowValues[] = 'NULL';
                            } elseif (is_numeric($value)) {
                                $rowValues[] = $value;
                            } else {
                                $rowValues[] = "'" . addslashes($value) . "'";
                            }
                        }
                        
                        $values[] = "  (" . implode(', ', $rowValues) . ")";
                    }
                    
                    $sql .= implode(",\n", $values) . ";\n\n";
                }
            } else {
                $sql .= "-- Таблица `{$table}` пуста\n\n";
            }
        }
        
        $sql .= "SET FOREIGN_KEY_CHECKS=1;\n";
        
        return $sql;
    }
    
    private function compressBackup(string $sqlFileName, string $backupName): string
    {
        $zipFileName = "{$backupName}.zip";
        $sqlPath = Storage::disk('backups')->path($sqlFileName);
        $zipPath = Storage::disk('backups')->path($zipFileName);
        
        $zip = new ZipArchive();
        if ($zip->open($zipPath, ZipArchive::CREATE) === TRUE) {
            $zip->addFile($sqlPath, $sqlFileName);
            $zip->close();
            
            Storage::disk('backups')->delete($sqlFileName);
            
            return $zipFileName;
        }
        
        throw new \Exception('Не удалось создать ZIP архив');
    }
    
    private function getBackupFiles(): array
    {
        $files = [];
        $backupFiles = Storage::disk('backups')->files();
        
        foreach ($backupFiles as $file) {
            $files[] = [
                'name' => $file,
                'size' => $this->formatBytes(Storage::disk('backups')->size($file)),
                'date' => Carbon::createFromTimestamp(
                    Storage::disk('backups')->lastModified($file)
                )->format('d.m.Y H:i:s'),
                'type' => pathinfo($file, PATHINFO_EXTENSION),
            ];
        }
        
        usort($files, function ($a, $b) {
            return strtotime($b['date']) - strtotime($a['date']);
        });
        
        return $files;
    }
    
    private function formatBytes($bytes, $precision = 2): string
    {
        $units = ['B', 'KB', 'MB', 'GB', 'TB'];
        
        $bytes = max($bytes, 0);
        $pow = floor(($bytes ? log($bytes) : 0) / log(1024));
        $pow = min($pow, count($units) - 1);
        
        $bytes /= pow(1024, $pow);
        
        return round($bytes, $precision) . ' ' . $units[$pow];
    }
}